name: Publish jar

on:
  push:
    branches:
      - next

jobs:
  release:
    name: Publish to Sonatype
    runs-on: ubuntu-20.04
    if: "startsWith(github.event.head_commit.message, 'chore: release')"
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_PRIVATE_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PRIVATE_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version-file: .java-version
          cache: gradle

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Upload Artifacts
        run: ./gradlew clean publish --no-parallel --stacktrace

      - name: Check snapshot
        id: snapshot
        run: |
          if [[ $(cat ./gradle.properties | grep 'VERSION_NAME=.*-SNAPSHOT') ]]; then
            echo "IS_SNAPSHOT=true" >> $GITHUB_OUTPUT
          fi

      - name: Release Artifacts
        if: ${{ steps.snapshot.outputs.IS_SNAPHOT != 'true' }}
        run: ./gradlew closeAndReleaseRepository
